### ISSUE TITLE
iTunes artwork will not update

### ISSUE THREAD

**Issue by miyaoka** [soussune/soussune.com#104]
https://itunes.apple.com/jp/podcast/soussune/id1247135079

![image](https://user-images.githubusercontent.com/1443118/40149847-1790cb06-59b1-11e8-8062-cab9e8dbbfbb.png)

## :warning:  問題

昔のロゴ無しartworkがキャッシュされたまま

## :speech_balloon:  識者の意見

> Apple Podcastsガ　バカ　ダッタラ　URL　カエルダケデ　ナオルノカナトカ
オモッテミタ

---

## :information_source:  参考：Appleがばかなのかもしれないと思うところ

<img src="https://user-images.githubusercontent.com/1443118/40150730-73d88d2c-59b6-11e8-815d-6141dc375c38.png" height="400"><img src="https://user-images.githubusercontent.com/1443118/40150736-7ca1831e-59b6-11e8-978d-c8925e13a2a3.png" height="400">

検索で、勝手にひらがな化したタイトルを候補に出しておいて、そっちを選択すると結果が無いと言う（つらい）

**Comment by trkw** [comment]
カバーアートの対応としては、ファイル名の変更かフォルダの変更で、一度試したいかもです。

NetlifyのCacheの設定に乗せられるようだったら、何かフォルダを作成してその配下で一括でCache-Control、Expiresの設定もついでにできるといいかも。
icons系が乱雑においてあるので。

**Comment by trkw** [comment]
カバーアートの画像URLを変えても更新がされていない事を確認

**Comment by trkw** [comment]
個々のEpisodeのカバーアートが500kb以上の可能性があるため、各エピソードのカバーアートを
更新すると直るかも？

**Comment by miyaoka** [comment]
個々のエピソードってmp3に埋め込まれてる感じ？
変えるの面倒だけど、サイズでかいから減量したやつにしていきたいね

**Comment by trkw** [comment]
そう。昨日圧縮したjpgを埋め込んだmp3をcontentfulには上げているで、あとは各mdにそれを適用すること感じだけど、その辺の更新が怠いんだなぁと今更感じてた

**Comment by trkw** [comment]
熊本の行きの、新幹線から確認。

<img width="1063" alt="2018-05-25 14 38 13" src="https://user-images.githubusercontent.com/2557813/40527845-534dc59e-6029-11e8-8607-e8c012397dd2.png">

mp3の更新によって上記のようにiTunes Previewのアートワークが更新されていることが確認されたので、このIssueをクローズします。
