### ISSUE TITLE
The copyright year is not current year

### ISSUE THREAD

**Issue by miyaoka** [soussune/soussune.com#105]
![image](https://user-images.githubusercontent.com/1443118/40149847-1790cb06-59b1-11e8-8062-cab9e8dbbfbb.png)

## ここ

> © 2017 soussune

あるある

## 対策

- copyright要るよ派
  - 年情報も要るよ派
    - 1: フィード生成時に自動でgenerate時の年を設定する
      - 生成時だからリリースしないと更新はされない
  - 年情報要らないよ派
    - 2: 年を省いてsoussuneだけにしとく
 - copyright要らないよ派
   - 3: 著作権は著作者にあるのが自明だから言うまでもない。よってcopyright自体省く

3かな

**Comment by trkw** [comment]
3かな

**Comment by trkw** [comment]
copyrightの削除が完了し、確認したのでクローズします。
