### ISSUE TITLE
Missing og image for facebook

### ISSUE THREAD

**Issue by miyaoka** [soussune/soussune.com#115]
![image](https://user-images.githubusercontent.com/1443118/43500084-bc0ab890-9589-11e8-9c91-3ccec0020289.png)

**Comment by trkw** [comment]
ogpのサイズがあれですが表示されてる

<img width="1396" alt="2018-08-01 12 55 13" src="https://user-images.githubusercontent.com/2557813/43500156-2940e696-958a-11e8-8f42-b91ebf6aebe0.png">

**Comment by miyaoka** [comment]
すまんキャッシュだった :cry:

**Comment by trkw** [comment]
Facebook Debuggerの仕様かどうかあれなんですけど、2度スクレイピングしないとOGPイメージ拾わなかったりするです

**Comment by miyaoka** [comment]
ついでなのでep34の画像パスが古かったので直した
