### ISSUE TITLE
Header layout is broken

### ISSUE THREAD

**Issue by miyaoka** [soussune/soussune.com#50]
<img src="https://user-images.githubusercontent.com/1443118/36086984-ebfa871c-1012-11e8-8e03-7b9f22f9a986.png" height="500">

on iOS9

**Comment by iwag** [comment]
:eyes:

**Comment by miyaoka** [comment]
iOS9でもう再現環境無いけど、下手にgridでレイアウトしてるせいな気はするので、ちょっとコンポーネント整理していきたい
