### ISSUE TITLE
Optimize bundle size

### ISSUE THREAD

**Issue by miyaoka** [soussune/soussune.com#61]
`nuxt build -a`で確認

<img width="984" alt="2018-04-08 17 23 45" src="https://user-images.githubusercontent.com/1443118/38465014-a7b85b46-3b51-11e8-9ba8-70a83abebea6.png">

- 安直にfont awesomeアイコン全読みしてしまってそのサイズが大きいので必要なものだけにする
- ravenも各ページで読まれてしまっている模様

**Comment by trkw** [comment]
https://github.com/soussune/soussune.com/pull/62
