### ISSUE TITLE
Unable to install npm package

### ISSUE THREAD

**Issue by trkw** [soussune/soussune.com#66]
**OS**
macOS High Sierra 10.13.3

**node**
v9.4.0

**npm version**
5.6.0

`npm i`でインストールすると以下のようなエラーがでるが、
`yarn`からインストールすると問題がないため報告

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "npm:": npm:nuxt-edge

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trkw/.npm/_logs/2018-04-10T08_27_22_786Z-debug.log
```

**Comment by miyaoka** [comment]
あ、nuxt-edgeを指定しているところ、
`    "nuxt": "npm:nuxt-edge", `
はyarnのみ有効っぽい

まあvueはyarn標準らしいのでyarn専用でいいかなと

**Comment by trkw** [comment]
> まあvueはyarn標準らしいのでyarn専用でいいかなと
ほい

じゃREADMEをyarnに書き直しておいて欲しいかなぁ

**Comment by miyaoka** [comment]
nuxt-edgeにしてるのは一時的なものだけど、
yarn.lockもあるしyarn専用なREADMEに書き換えました

**Comment by trkw** [comment]
はい。修正されているのを確認しましたので、クローズしますー
