### ISSUE TITLE
Jumbotron style in sp-mode is broken!

### ISSUE THREAD

**Issue by miyaoka** [soussune/soussune.com#81]
<img width="555" alt="2018-04-23 23 53 35" src="https://user-images.githubusercontent.com/1443118/39134474-ab387c9a-4751-11e8-8d3c-db92e4adadac.png">

wa-o

**Comment by trkw** [comment]
https://github.com/soussune/soussune.com/pull/82 こちらで対応をしたので、一度クローズします。SP modeの時もStorybookで検知できるようにします。
