### ISSUE TITLE
Add realname field for actor

### ISSUE THREAD

**Issue by miyaoka** [soussune/soussune.com#92]
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">そういやmiyaokaさんって宮岡さんじゃないってマジなんですか</p>&mdash; potato4d (@potato4d) <a href="https://twitter.com/potato4d/status/995889056176226305?ref_src=twsrc%5Etfw">May 14, 2018</a></blockquote>

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">昨日「どうも花谷ですー」って言って後から「あっpotato4dさんすか！」ってなるのと「どっちで呼ぶと良いですか」みたいなの無限にあったので計画的に名義使わないと人を混乱させてしまうことがわかった</p>&mdash; potato4d (@potato4d) <a href="https://twitter.com/potato4d/status/996538051412164608?ref_src=twsrc%5Etfw">May 15, 2018</a></blockquote>

id、表示名以外に、実名表示用のプロパティを追加したい

```
actorId: miyaoka
title: miyaoka
realname: Masaya Kazama
```
↓
```
miyaoka (Masaya Kazama)
```

realnameある場合のみ（）で表示するイメージ
表示が長くなるので、actor一覧、actor詳細でのみ出す想定

**Comment by trkw** [comment]
Cardの複数行対応が辛いため詳細のみを対応してクローズ。
