### ISSUE TITLE
Closed tag is not generated

### ISSUE THREAD

**Issue by trkw** [soussune/soussune.com#94]
![2018-05-16 18 05 52](https://user-images.githubusercontent.com/2557813/40107656-d32487f0-5933-11e8-8b14-26eaad5f6204.png)

**Comment by miyaoka** [comment]
たしかに閉じhtmlタグ無いなー。なんだこれ

**Comment by trkw** [comment]
調べてみたところ、removeOptionalTagsを付与することで解決されることが分かった。
ただ、これはモダンなブラウザでは不要なタグとして判定してnuxtがgenerate時に削っているようです。

**Comment by trkw** [comment]
気持ちが悪いから対応したいけどどう思います？

**Comment by miyaoka** [comment]
ふーむ
nuxtが、ってよりはwebpackのminifyの標準がこれってことかな？
標準でこれならいいと思う

**Comment by trkw** [comment]
じゃクローズします〜

**Comment by miyaoka** [comment]
タグチェックツールで検査するの自体がもはやレガシーか

**Comment by trkw** [comment]
https://github.com/kangax/html-minifier

これ使ってるみたいなので自分用にメモ
