### ISSUE TITLE
og:image of actor page not shown

### ISSUE THREAD

**Issue by miyaoka** [soussune/soussune.com#98]
![image](https://user-images.githubusercontent.com/1443118/40117816-0733b4ca-5953-11e8-9d7b-323d9bfca681.png)

```
<meta
  data-n-head="true" 
  content="//images.ctfassets.net/gvze4h7pavn2/15dtnG0XJIWCQqCwcumYMK/23033d60017d92878bb05427eaf50700/actor-miyaoka.jpg"
  data-hid="ogImage"
  property="og:image"
>
```

これもスキームつけてないせいかな？

**Comment by trkw** [comment]
そうっすね。それスキームつければ読み込めるので、埋め込んでから

**Comment by trkw** [comment]
![2018-05-16 22 07 56](https://user-images.githubusercontent.com/2557813/40118756-c0d32dbe-5955-11e8-9cbb-dd66e91e81fe.png)

LGTM
